### ISSUE TITLE
$GOPATH and $GOBIN not set, wrong URL on aur-page

### ISSUE THREAD

**Issue by timhae** [Deluxo/gotwitch#1]
two things I would like to add to this neat tool:

your Upstream URL on your [aur page](https://aur.archlinux.org/packages/gotwitch/) points nowhere.

and

I had to set $GOPATH and $GOBIN manually, otherwise the installation would fail, also see [this SO question](http://stackoverflow.com/questions/26134975/go-install-no-install-location-for-directory-outside-gopath) and output of `go env` after those adjustments:

```bash
~/ go env
GOARCH="amd64"
GOBIN="/tmp/yaourt-tmp-tim/aur-gotwitch/src/gotwitch/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/yaourt-tmp-tim/aur-gotwitch/src/gotwitch"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build451840183=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

and as improvement maybe tab-completion so i can browse most-viewed games, select the game I'd like to watch and then select a stream :)

**Comment by timhae** [comment]
I wrote a shell script for the improvement part:

```bash
#!/bin/bash
PS3="Select Game:"
select game in $(gotwitch games | sed -e 's/ /%20/g')
do
    if [ -n "$game" ]; then

    PS3="Select Stream:"
    select stream in $(gotwitch streams -g $game)
    do
        if [ -n "$stream" ]; then
            gotwitch watch -s $stream
            exit
        fi
    done

    fi
done
```

**Comment by Deluxo** [comment]
# Dear TimboJones!

Hello!

Im pleased you took interest in my little app.
The completion acually exists! I just did a bare minimum with the time i have to release it.

## To address the tab-completion

enter this command in the shell session or better yet, your shell rc:
`eval "$(gotwitch --completion-script-zsh)"`
or if you use bash:
`eval "$(gotwitch --completion-script-bash)"`

I will update the repo and the aur package this weekend probably.

## As for the easy to use prompt:

I personally use rofi, so i did a little dmenu-ish script to do just that:

![1480970824](https://cloud.githubusercontent.com/assets/3360414/20901781/cf399d2e-bb3c-11e6-8612-4fce1511eb09.png)
![1480970838](https://cloud.githubusercontent.com/assets/3360414/20901782/cf3b1e4c-bb3c-11e6-9831-e71411edfe4b.png)

### the script

```bash

#! /bin/sh

if [ -z "$@" ]
then
	echo Subscribtions;
	echo Popular
else
	if [ "$@" == "Subscribtions" ]; then
		gotwitch streams -b
	elif [ "$@" == "Popular" ]; then
		gotwitch streams
	else
		channel=$(echo $@ | awk '{print $1;}')
		gotwitch -s $channel
	fi
fi
```
## Follow up

Would you mind taking a liberty to make MR or fork it, or specifying what exactly is still missing, except your mentioned issues here?

I'd love to make it better, whenever i can!
I'll try to fix your problems this week.

Cheers!

**Comment by timhae** [comment]
Hey,

thanks for your quick response.

> Would you mind taking a liberty to make MR or fork it, or specifying what exactly is still missing, except your mentioned issues here?

Sadly I don't know what MR is. As for a fork, I don't know the language Go and how to build AUR packages/writing PKGBUILDs, which I probably need to implement the changes.

If you are asking for my whishlist, here you go:

* Add a ncurses GUI with vim-like Keybingings, thats all :) (Implementing might not be as easy as saying it though)
* Maybe don't require a login (watch as unregistered user). That way one would loose the ability to watch subscribed channels but you would not have to go through the OAuth registration process

other than that I am completely satisfied with your tool.

Greetings,
Tim

PS: your desktop looks nice, what window manager do you use?

**Comment by Deluxo** [comment]
Bspwm with polybar, conky, some wallpaper from wallhaven.cc and colors taken from a wallpaper.
